[project]
name = "mediagent"
version = "0.1.0"
description = "Agent that answers medical questions based on evidence"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "logfire>=4.4.0",
    "metapub>=0.6.4",
    "notebook>=7.4.5",
    "pydantic-ai-slim[google,openai]>=1.0.1",
    "pydantic-graph>=1.0.1",
]

[tool.ruff]
line-length = 99
exclude = [
    ".venv",
    "venv",
    ".git",
    ".pyenv",
    "__init__.py",
    ".ipynb_checkpoints",
    ".ruff_cache",
    "__pycache__"
]
ignore = [
    "F541" #f-string without any placeholders
]
